200 – 300 gms Macroni.

Water (for Boiling macroni).

1.5 tsp Salt (while boiling macroni).

2 Onion.

2 Tomatoes.

1 Capsicum.

Few French Beans.

½ Carrot.

7 – 8 Garlic Cloves.

1 Inch Ginger.

¼ Cup Peas.

1 tsp Salt (While Making Masala).

1 tsp Red Chilli Powder.

½ tsp Haldi Powder.

1 tsp Coriander Powder.

1 tsp Garam Masala.

½ tsp Amchoor.

Lots of Tomato Ketchup.